### PR TITLE
Changed monokai to Monokai to keep consistency

### PR DESCRIPTION
**Pull request by m0khi**
to keep consistency for downstream plugins, i suggest having "Monokai" all situations instead of "monokai" OR renaming file to "monokai" instead of "Monokai"

### CODE REVIEW

**Comment by liloman** [comment]
WTF???

Almost a year to change a case??

I don't want to resigne and use my fork but man ...

**Comment by m0khi** [comment]
Then how much usually we should wait for it to be merged ? :smiley:

**Comment by liloman** [comment]
Who knows!. 

Take it easy. :D

**Comment by flazz** [comment]
Sorry folks for the wait been super busy in life. I think the other PR fixed this, no?

**Comment by m0khi** [comment]
> Sorry folks for the wait been super busy in life.
np ;)
> I think the other PR fixed this, no?
AFAIK, and since my last use of it, no!

**Comment by m0khi** [comment]
Thanks :+1:

**Comment by liloman** [comment]
Just in time. :)

**Pull request merged**
