### PR TITLE
Add 75 New Colors

### PR DESCRIPTION
**Pull request by JohnRobson**
Add 75 New Colors & Fix Some Colors

### CODE REVIEW

**Comment by flazz** [comment]
it all looks good except midnight2.vim seems to be deleted, what is the deal with that?

**Comment by JohnRobson** [comment]
I did not tested everyone, but all I tested worked. I hope that this helps to complete this plugin.

**Comment by JohnRobson** [comment]
The filename is: midnight.vim

I changed the name from "midnight2" to "midnight"

**Comment by JohnRobson** [comment]
let me know if everything is ok

**Pull request merged**
