### PR TITLE
Updating colorschemes from vimcolors.com

### PR DESCRIPTION
**Pull request by KurtPreston**
Re-ran the vimcolors retrieval script (on the prep branch) to get updated color schemes.

### CODE REVIEW

**Comment by wwwdata** [comment]
hm, this is weird, after this merge, everything is broken for me. I was using the `railscasts` theme and previously everything was looking fine like this: 
screen shot 2016-03-13 at 21 01 39

But after your commit, my `railscasts` theme is broken and looks like this: 
screen shot 2016-03-13 at 21 02 43

wrong colors in iTerm2 with neovim 1.2 and vim version 7.4

**Comment by wwwdata** [comment]
I look at the diff and noticed that it now says `A GUI Only port ...`

could it be that you accidentally merged some wrong themes?

**Comment by KurtPreston** [comment]
It looks like there's multiple different colorschemes listed on vimcolors.com with the name ```railscasts```.  With the last update, the referenced colorscheme got switched.

1. ```git@github.com:/justincampbell/vim-railscasts``` <--- the one currently on master
2. ```git@github.com:/chankaward/vim-railscasts-theme``` <--- the one previously used

I did a quick review, and it looks like 5 of the 200 colorschemes pulled from vimcolors have duplicate names.

In the case of competing names, the vimcolor retrieval script is currently arbitrarily selecting whichever theme comes last in the path.

Not sure the best way to deal with these ambiguities.  Any suggestions?

**Comment by wwwdata** [comment]
Hm, the old "correct" one also has the most github stars. Maybe the script could also look at the stars and in case of a name conflict pull the theme with the most?

**Comment by KurtPreston** [comment]
I like that idea!  I tried your suggestion and updated the colors.  See pull request https://github.com/flazz/vim-colorschemes/pull/93

The good news: it works.
The bad news: there's an even *more* popular railscasts theme that it's now pulling:
https://github.com/jpo/vim-railscasts-theme

It's different from what you were using before, but seems similar.  Given the number of stars (203), it probably is closer to the "original".

**Comment by wwwdata** [comment]
cool, yes that other theme looks good and also has the options for terminal

**Comment by zachgersh** [comment]
@wwwdata should be fixed now thanks to @KurtPreston

**Pull request merged**
