### PR TITLE
Fixes #122

### LINKED ISSUE #122: File conflict on Windows
Hi there,

Commit 613bd695916ab14db6f2463edf9e49d3236b179d added a new `darkBlue.vim` scheme, but on Windows, which has a case-insensitive file-system, that conflicts with the existing `darkblue.vim` (note the lowercase "b").

I don't know if there's a better solution than this, but renaming that new one to `darkblue3.vim` would definitely be the simplest?

### PR DESCRIPTION
**Pull request by metcalfc**
Fixes the file system case sensitivity issue in #122

### CODE REVIEW

**Comment by mrap** [comment]
Leggo already!

**Comment by metcalfc** [comment]
@flazz just a quick ping here. No rush. I know you're busy.

**Comment by isaachier** [comment]
Please accept to fix #122 @flazz.

**Comment by flazz** [comment]
lets discuss in #163

**Pull request closed without merging**
